GET http://localhost:8880/hello
#Accept: application/json

> {%
client.test("test-hello", function() {
  client.log("测试hello");
  client.log(response.body);
  client.log(JSON.stringify(response.body));
  client.assert(response.status === 200, "返回码不是200");
  client.assert(response.body === "Hello","结果验证失败");
})
%}
###

POST http://localhost:8880/api/item
Content-Type: application/x-www-form-urlencoded

id=99&content=new-element

###

// gtr
GET http://localhost:8881/test/list
Accept: application/json

###